# NyX.x.OS Kitty Terminal
font_family      JetBrains Mono Nerd Font
font_size        12.0
background       #111111
foreground       #C8C0C0
cursor           #C8C0C0
cursor_shape     beam
selection_background #7B5EA733
background_opacity 1.0

# Window
window_padding_width 12
window_margin_width 0
draw_minimal_borders yes
window_border_width 1px
active_border_color #7B5EA7
inactive_border_color #2A2020

# Colors
color0  #0A0A0A
color1  #8B4040
color2  #4A7B5E
color3  #7B6E4A
color4  #4A5E7B
color5  #7B5EA7
color6  #4A7B7B
color7  #C8C0C0
color8  #3A3030
color9  #C4607A
color10 #5EA77B
color11 #A7955E
color12 #5E7BA7
color13 #7B5EA7
color14 #5EA7A7
color15 #E8E0E0

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_background #7B5EA7
active_tab_foreground #080808
inactive_tab_background #0D0B0B
inactive_tab_foreground #6A6060

# Startup
startup_session none
